### ISSUE TITLE
Error installing through pip

### ISSUE THREAD

**Issue by riyadparvez** [TimeSynth/TimeSynth#12]
This is the error log:

```
Collecting timesynth
  Downloading https://files.pythonhosted.org/packages/90/10/db1a380cbff37963d775e4104d3566c956ea4726f5f51dc6bc3f6b693f01/timesynth-0.2.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rbmeb8l4/timesynth/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rbmeb8l4/timesynth/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-rbmeb8l4/timesynth/pip-egg-info
         cwd: /tmp/pip-install-rbmeb8l4/timesynth/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rbmeb8l4/timesynth/setup.py", line 9, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by 1Reinier** [comment]
Fixed in 0.2.4.
