### ISSUE TITLE
AR Model Sample fails

### ISSUE THREAD

**Issue by gibbs-hmm** [TimeSynth/TimeSynth#23]
import timesynth as ts

# Initializing TimeSampler
time_sampler = ts.TimeSampler(stop_time=20)
# Sampling regular time samples
regular_time_samples = time_sampler.sample_regular_time(num_points=500)

 Initializing AR(2) model
ar_p = ts.signals.AutoRegressive(ar_param=[1.5, -0.75])
ar_p_series = ts.TimeSeries(signal_generator=ar_p)
samples = ar_p_series.sample(regular_time_samples)

Fails with error 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bill/mambaforge/envs/nn/lib/python3.11/site-packages/timesynth/timeseries.py", line 63, in sample
    signal = self.signal_generator.sample_next(t, samples[:i - 1], errors[:i - 1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bill/mambaforge/envs/nn/lib/python3.11/site-packages/timesynth/signals/ar.py", line 54, in sample_next
    ar_value = np.sum(ar_value) + noise
               ^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in sum
  File "/home/bill/mambaforge/envs/nn/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 2324, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bill/mambaforge/envs/nn/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
>>>

Running with Python 3.11.3

**Comment by Hamiedamr** [comment]
```python
class FixedAutoRegressive(ts.signals.AutoRegressive):
    def sample_next(self, time, samples, errors):
        ar_value = [self.previous_value[i] * self.ar_param[i] for i in range(len(self.ar_param))]
        noise = np.random.normal(loc=0.0, scale=self.sigma, size=1)
        ar_value = np.sum(ar_value) + float(noise)
        self.previous_value = self.previous_value[1:] + [ar_value]
        return ar_value

```
This temp solution will fix it

**Comment by hernandojDeAvil4** [comment]
Hi guys, Some one has the code fixed withou the nedd of use the class FixedAutoRegressive ?
