### ISSUE TITLE
import ts raises ModuleNotFoundError: No module named 'symengine'

### ISSUE THREAD

**Issue by subrata4096** [TimeSynth/TimeSynth#8]
>>> import timesynth as ts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sumitra/work/TimeSynth/timesynth/__init__.py", line 2, in <module>
    from . import signals
  File "/Users/sumitra/work/TimeSynth/timesynth/signals/__init__.py", line 5, in <module>
    [_basename(f)[:-3] for f in _glob.glob(_dirname(__file__) + "/*.py") \
  File "<string>", line 4, in <module>
  File "/Users/sumitra/work/TimeSynth/timesynth/signals/dde.py", line 6, in <module>
    from jitcdde import y, t, jitcdde
  File "/Users/sumitra/work/scheduling/venv/lib/python3.7/site-packages/jitcdde-1.3.1-py3.7.egg/jitcdde/__init__.py", line 1, in <module>
  File "/Users/sumitra/work/scheduling/venv/lib/python3.7/site-packages/jitcdde-1.3.1-py3.7.egg/jitcdde/_jitcdde.py", line 6, in <module>
ModuleNotFoundError: No module named 'symengine'

**Comment by Smittie123** [comment]
Same issue here, using Python 3.7..

**Comment by 1Reinier** [comment]
I’ll take a look

**Comment by capaulson** [comment]
I had the same issue, but just needed to upgrade cython. Symengine was failing to build. Hope that helps.

**Comment by glitchySoftware** [comment]
> I had the same issue, but just needed to upgrade cython. Symengine was failing to build. Hope that helps.

He capaulson, can you elaborate what you did? I upgraded Cython but still does not work..

**Comment by 1Reinier** [comment]
Replicated this issue in Travis for Python 3.7. Will fix soon.

**Comment by 1Reinier** [comment]
should work now

**Comment by glitchySoftware** [comment]
Thanks Reinier but.. tried with a fresh virtualenv but now I am getting the following error: ModuleNotFoundError: No module named 'jitcdde'..

**Comment by glitchySoftware** [comment]
@1Reinier Got it working by running pip install jitcdde==0.32

**Comment by 1Reinier** [comment]
Happy that that's working for you. Jenkins seems to work fine for both python 3.5 and 3.7 with this setup, so I might leave it this way for now.

**Comment by lv-bakker** [comment]
Hi, I've got the same problem as Subrata. 
`Traceback (most recent call last):
  File "C:/Users/leon.bakker/stack/Leon/Master Information Sciences/Master project/BearingPoint/demandlib-master/demandlib/examples/heat_demand_example.py", line 24, in <module>
    import timesynth as ts
  File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timesynth-0.2.4-py3.8.egg\timesynth\__init__.py", line 2, in <module>
    from . import signals
  File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timesynth-0.2.4-py3.8.egg\timesynth\signals\__init__.py", line 4, in <module>
    exec('\n'.join(map(lambda name: "from ." + name + " import *", 
  File "<string>", line 4, in <module>
  File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timesynth-0.2.4-py3.8.egg\timesynth\signals\dde.py", line 6, in <module>
    from jitcdde import y, t, jitcdde
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jitcdde-1.4.0-py3.8.egg\jitcdde\__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jitcdde-1.4.0-py3.8.egg\jitcdde\_jitcdde.py", line 6, in <module>
ModuleNotFoundError: No module named 'symengine'

Process finished with exit code 1
`

Any idea how I can fix this? I've got python 3.7.4 and symengine 0.4 installed.

**Comment by lv-bakker** [comment]
> Hi, I've got the same problem as Subrata.
> `Traceback (most recent call last):
> File "C:/Users/leon.bakker/stack/Leon/Master Information Sciences/Master project/BearingPoint/demandlib-master/demandlib/examples/heat_demand_example.py", line 24, in
> import timesynth as ts
> File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timesynth-0.2.4-py3.8.egg\timesynth__init__.py", line 2, in
> from . import signals
> File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timesynth-0.2.4-py3.8.egg\timesynth\signals__init__.py", line 4, in
> exec('\n'.join(map(lambda name: "from ." + name + " import *",
> File "", line 4, in
> File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\timesynth-0.2.4-py3.8.egg\timesynth\signals\dde.py", line 6, in
> from jitcdde import y, t, jitcdde
> File "", line 259, in load_module
> File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jitcdde-1.4.0-py3.8.egg\jitcdde__init__.py", line 1, in
> File "", line 259, in load_module
> File "C:\Users\leon.bakker\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jitcdde-1.4.0-py3.8.egg\jitcdde_jitcdde.py", line 6, in
> ModuleNotFoundError: No module named 'symengine'
> 
> Process finished with exit code 1
> `
> 
> Any idea how I can fix this? I've got python 3.8.1 and symengine 0.4 installed.

Sorry for the comment :) I did everything again in a conda environment and it worked.

**Comment by swight-prc** [comment]
Is there anything about `symengine>0.4` that breaks TimeSynth? Because `==0.4.0` is keeping you in 3.7.

**Comment by CubeBot888** [comment]
For TimeSynth use with Python 3.8, perhaps implement the change in setup.py as per this unmerged pull request: https://github.com/TimeSynth/TimeSynth/pull/20/files
Or do: pip install --upgrade symengine==0.6.1
